### ISSUE TITLE
Exception raised after compiling with pyinstaller

### ISSUE THREAD

**Issue by VXsz** [LBeaudoux/iso639#11]
After compiling with pyinstaller I keep getting this error:
```
test\dist>test.exe
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "iso639\iso639.py", line 68, in __new__
iso639.exceptions.InvalidLanguageValue: (*('ja',), **{}). Only valid ISO 639 language values are supported as arguments.
[10072] Failed to execute script 'test' due to unhandled exception!
```
Not sure why, perhaps I need to add some data with pyinstaller but I feel like it won't help since that's not the issue I think here
My guess would be some args passing issue (probably)

my original python code is simply these lines
```py
from iso639 import Lang
print(Lang('ja').name)
```
then compiled using pyinstaller (installed through pip) with this command: `pyinstaller test.py --onefile`

**Comment by LBeaudoux** [comment]
I am not familiar with pyinstaller but it seems to me that you have to add the necessary .json and .pkl  data files found in 
`iso639/data/` to your bundle as explained [here](https://pyinstaller.readthedocs.io/en/latest/spec-files.html#adding-data-files).

The `iso639.exceptions.InvalidLanguageValue` exception is misleading.  It is raised because preceding `FileNotFoundError` exceptions are caught in the [iso639.datafile](https://github.com/LBeaudoux/iso639/blob/master/iso639/datafile.py) module when the loading of mappings fails (which in retrospect seems like a bad idea).

**Comment by VXsz** [comment]
I see, after a bit of trying `--add-data "C:\Users\ivxsz\AppData\Local\Programs\Python\Python39\Lib\site-packages\iso639;./iso639"` worked perfectly

Also thank you so much for this library, it saved me a lot of headaches & a huge amount of time

**Comment by jlw4049** [comment]
I know this is old, but I put in a PR to pyinstallers hooks contrib here https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/707
